title: Andy's Git Site
author: Andy
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blah, blah, blah, blah

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: Minima
